### ISSUE TITLE
package combination

### ISSUE THREAD

**Issue by simonfranz** [ricbra/php-discogs-api#24]
HI there,
At first thanks for this awesome package :-).

I'm trying to get this package with "robbiep/cloudconvert-laravel" to work. But  this package needs "guzzlehttp/guzzle": "~5.0".

Sadly php-discogs-api has a dependency for "guzzlehttp/guzzle": "~4.0", so it seems that these 2 packages are not compatible.

Is it planned to update this package to work with guzzle 5.0 ?

Best Regards

**Comment by ricbra** [comment]
Hi @simonfranz ,

Thanks for reporting this issue, I wasn't aware of the new Guzzle update. I'll try to update the library when I find the time.

**Comment by simonfranz** [comment]
it's not really an issue, but it would be nice to be on 5.*
thanks for locking into this

**Comment by ricbra** [comment]
Fixed in https://github.com/ricbra/php-discogs-api/pull/25

**Comment by Bodstodon** [comment]
Hi,

The current version of guzzle seems to be 6.3.3. Any chance for 6.x support?

**Comment by ricbra** [comment]
Hi @Bodstodon could you open a new issue for that? Also, Guzzle had a major refactoring since version 5 so it would require a decent amount of time to get it working. If this is something you want to work on, I woud be more then happy to merge your pull request for that 😄
