### ISSUE TITLE
How to create $services object?

### ISSUE THREAD

**Issue by deepak-netwin** [ricbra/php-discogs-api#50]
Hi there,

Thanks for this module!
Can you please let me know how can I create $services object to access method:

```
$release = $service->getRelease([
    'id' => 1
]);
```

**Comment by ricbra** [comment]
Hi @deepak-netwin 

In the documentation sometimes `$client` is used as name and sometimes `$service`. But they are both the same. So perhaps this makes more sense to you:

```php
$release = $client->getRelease([
    'id' => 1
]);
```

**Comment by deepak-netwin** [comment]
@ricbra Thanks for your reply. I tried with the same and able to get the release details.

**Comment by ricbra** [comment]
Nice
